# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hermit Engine
email: hermit@hermitengine.com

#write html inside the double quotes to display in jumbotron
description: "<h1>Hermit Engine</h1><h3>Sometimes you have to do it on your own</h3>"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.hermitengine.com" # the base hostname & protocol for your site
twitter_username: ""
github_username:  hermitengine

# Build settings
markdown: kramdown
